# Generated by Django 3.2.13 on 2022-05-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('role', models.IntegerField(choices=[(321, 321), (987, 987)], default=321)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_style', models.IntegerField(default=1)),
            ],
        ),
    ]
