# Generated by Django 3.2.13 on 2022-05-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_alter_all_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
