# Generated by Django 3.2.13 on 2022-05-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_all_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('established', models.DateField(blank=True, null=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='travels.all_users')),
            ],
        ),
        migrations.CreateModel(
            name='Agency_trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_urll', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type_of_travel', models.CharField(choices=[('samostalno', 'samostalno'), ('organizovano', 'organizovano')], max_length=100)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('min_number', models.IntegerField()),
                ('max_number', models.IntegerField()),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_transport', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='travels.all_users')),
            ],
        ),
        migrations.CreateModel(
            name='User_Agency_trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('na čekanju', 'na čekanju'), ('odobreno', 'odobreno'), ('odbijeno', 'odbijeno')], default='na čekanju', max_length=100)),
                ('agency_trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agg', to='travels.agency_trips')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='travels.user')),
            ],
        ),
        migrations.AddField(
            model_name='agency_trips',
            name='transport',
            field=models.ManyToManyField(to='travels.Transport'),
        ),
    ]
