# Generated by Django 3.2.13 on 2022-05-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20220525_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency_trips',
            old_name='image_urll',
            new_name='image_url',
        ),
    ]
