# Generated by Django 3.2.13 on 2022-05-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_agency_trips_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_trips',
            name='city_name',
            field=models.CharField(max_length=200),
        ),
    ]
