# Generated by Django 3.2.13 on 2022-06-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_remove_agency_trips_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_trips',
            name='image_url',
            field=models.TextField(blank=True, default='/media/default_img.jpg', null=True),
        ),
    ]
