# Generated by Django 3.2.13 on 2022-06-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_alter_agency_trips_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency_trips',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
