# Generated by Django 3.2.13 on 2022-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_agency_trips_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_trips',
            name='transport',
            field=models.ManyToManyField(blank=True, null=True, to='travels.Transport'),
        ),
    ]
